-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    balance NUMERIC(10, 2)
);

-- Categories
CREATE TABLE Categories (
    category_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

-- Products
CREATE TABLE Products (
    product_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id INT NOT NULL REFERENCES Users(id),
    category_id INT REFERENCES Categories(category_id),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    image_url TEXT,
    price DECIMAL(12,2) NOT NULL CHECK (price >= 0)
);

-- Carts
CREATE TABLE Carts (
    cart_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_id UNIQUE (user_id)
);

-- Cart_Items
CREATE TABLE Cart_Items (
    cart_item_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cart_id INT NOT NULL REFERENCES Carts(cart_id),
    product_id INT NOT NULL REFERENCES Products(product_id),
    seller_id INT REFERENCES Users(id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_cart_item UNIQUE (cart_id, product_id)
);

-- Orders
CREATE TABLE Orders (
    order_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    buyer_id INT NOT NULL REFERENCES Users(id),
    total_amount DECIMAL(12,2) NOT NULL CHECK (total_amount >= 0),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fulfillment_status VARCHAR(20) CHECK (fulfillment_status IN ('pending', 'partial', 'fulfilled')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Order_Items
CREATE TABLE Order_Items (
    order_item_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL REFERENCES Orders(order_id),
    product_id INT NOT NULL REFERENCES Products(product_id),
    seller_id INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    fulfillment_status VARCHAR(20) CHECK (fulfillment_status IN ('pending', 'fulfilled')),
    fulfilled_at TIMESTAMP
);

-- Product_Reviews
CREATE TABLE Product_Reviews (
    review_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INT NOT NULL REFERENCES Products(product_id),
    reviewer_id INT NOT NULL REFERENCES Users(id),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    image_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_product_review UNIQUE (reviewer_id, product_id)
);

-- Seller_Reviews
CREATE TABLE Seller_Reviews (
    seller_review_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id INT NOT NULL REFERENCES Users(id),
    reviewer_id INT NOT NULL REFERENCES Users(id),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    image_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_seller_review UNIQUE (reviewer_id, seller_id)
);

-- Inventory
CREATE TABLE Inventory (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(product_id),
    quantity_available INT NOT NULL CHECK (quantity_available >= 0),
    price DECIMAL(12,2) NOT NULL CHECK (price >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_inventory UNIQUE (seller_id, product_id)
);

-- Coupons
CREATE TABLE Coupons (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id INT NOT NULL REFERENCES Users(id),
    code VARCHAR(20) NOT NULL,
    discount_amount DECIMAL(12,2) NOT NULL CHECK (discount_amount > 0),
    expiration_date TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_coupon_code UNIQUE (code)
);

-- CREATE TABLE Products (
--     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name VARCHAR(255) UNIQUE NOT NULL,
--     price DECIMAL(12,2) NOT NULL,
--     available BOOLEAN DEFAULT TRUE
-- );

-- CREATE TABLE Purchases (
--     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     uid INT NOT NULL REFERENCES Users(id),
--     pid INT NOT NULL REFERENCES Products(id),
--     time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
-- );

-- CREATE TABLE Wishes (
--     id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     uid INT NOT NULL REFERENCES Users(id),
--     pid INT NOT NULL REFERENCES Products(id),
--     time_added timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
-- );

-- Add trigger to update Cart_Items price when Products price changes
CREATE OR REPLACE FUNCTION update_cart_items_price()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE Cart_Items
    SET unit_price = NEW.price
    WHERE product_id = NEW.product_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_cart_items_price_trigger
AFTER UPDATE OF price ON Products
FOR EACH ROW
EXECUTE FUNCTION update_cart_items_price();

-- Add trigger to update Products price when Inventory price changes
CREATE OR REPLACE FUNCTION update_products_price()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE Products
    SET price = NEW.price
    WHERE product_id = NEW.product_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_products_price_trigger
AFTER UPDATE OF price ON Inventory
FOR EACH ROW
EXECUTE FUNCTION update_products_price();
